Gh action add
elixir-cloud-aai/tesk-api pull request #45
Opened 2022-12-01 13:15 UTC by lvarin

- Add maven
- Add jdk8
- Add Dockerhub profile
- Changing Dockerhub repository
- Add Dockerfile option

2022-12-05 11:20 UTC, uniqueg requested changes
Thanks. Generally looking good, but CI generates warning due to security concerns with and depreciation of `set-output`. Updating all used actions should fix those issues.

![image](https://user-images.githubusercontent.com/10855418/205625014-58ed40f7-2017-4290-9901-c1217d80086f.png)

2022-12-05 11:20 UTC, uniqueg commented on .github/workflows/docker-build-publish.yml
> +        uses: actions/checkout@v2
Please update to v3

2022-12-05 11:20 UTC, uniqueg commented on .github/workflows/docker-build-publish.yml
> +        uses: docker/setup-qemu-action@v1
Please update to v2

2022-12-05 11:20 UTC, uniqueg commented on .github/workflows/docker-build-publish.yml
> +        uses: docker/setup-buildx-action@v1
Please update to v2

2022-12-05 11:20 UTC, uniqueg commented on .github/workflows/docker-build-publish.yml
> +        uses: docker/login-action@v1
Please update v2

2022-12-05 11:20 UTC, uniqueg commented on .github/workflows/docker-build-publish.yml
> +        uses: docker/metadata-action@v3
Please update to v4

2022-12-05 11:20 UTC, uniqueg commented on .github/workflows/docker-build-publish.yml
> +        uses: docker/build-push-action@v2
Please update to v3

2022-12-08 05:50 UTC, lvarin commented on .github/workflows/docker-build-publish.yml
> +        uses: docker/build-push-action@v2
done

2022-12-08 05:50 UTC, lvarin commented on .github/workflows/docker-build-publish.yml
> +        uses: docker/metadata-action@v3
done

2022-12-08 05:51 UTC, lvarin commented on .github/workflows/docker-build-publish.yml
> +        uses: docker/login-action@v1
done

2022-12-08 05:51 UTC, lvarin commented on .github/workflows/docker-build-publish.yml
> +        uses: docker/setup-buildx-action@v1
done

2022-12-08 05:51 UTC, lvarin commented on .github/workflows/docker-build-publish.yml
> +        uses: docker/setup-qemu-action@v1
done

2022-12-08 05:51 UTC, lvarin commented on .github/workflows/docker-build-publish.yml
> +        uses: actions/setup-java@v2
done

2022-12-08 05:51 UTC, lvarin commented on .github/workflows/docker-build-publish.yml
> +        uses: actions/checkout@v2
done

2022-12-08 07:50 UTC, lvarin commented
All warning seem to have disappeared.

2022-12-29 19:52 UTC, uniqueg approved these changes
Looks great :)

2022-12-29 19:55 UTC, merged