Add securityContext settings
elixir-cloud-aai/tesk-api pull request #46
Opened 2023-01-11 15:32 UTC by xhejtman

Add option to specify security context for Kubernetes pods

2023-01-12 10:48 UTC, martin-kuba requested changes

2023-01-13 21:57 UTC, xhejtman commented on pom.xml
> +            <version>1.21</version>
fixed

2023-01-13 22:20 UTC, xhejtman commented
@lvarin any idea how to fix these build fails?

2023-01-16 06:31 UTC, lvarin commented
It is complaining about:

https://github.com/elixir-cloud-aai/tesk-api/blob/3ca56c5c9b1fb9de025c5103ff260e1ae34434fb/src/test/java/uk/ac/ebi/tsc/tesk/k8s/convert/TesKubernetesConverterTest.java#L87

I am putting the link here, so I can find it later easier.

2023-01-16 15:43 UTC, lvarin commented
It took me whole day, but I got the problem. I will add the suggestions to a review, but the gist of it is that:

* The two ` @ContextConfiguration(classes = {io.kubernetes.client.openapi.apis.CoreV1Api.class})` should be removed
* coreAPi must be added to ` TesKubernetesConverterMinimalTest.java`:

```
@MockBean
private CoreV1Api coreApi;
``

2023-01-16 15:51 UTC, xhejtman commented
I wonder why it worked before merge from master.

2023-01-16 15:52 UTC, lvarin requested changes
The suggested changes should fix the tests. Please check if they make sense for you. I have not tested the change in OpenShift, but will do after these changes are committed.

2023-01-16 15:52 UTC, lvarin commented on src/test/java/uk/ac/ebi/tsc/tesk/k8s/convert/TesKubernetesConverterMinimalTest.java
> +@ContextConfiguration(classes = {io.kubernetes.client.openapi.apis.CoreV1Api.class})
```suggestion

```

2023-01-16 15:52 UTC, lvarin commented on src/test/java/uk/ac/ebi/tsc/tesk/k8s/convert/TesKubernetesConverterMinimalTest.java
```suggestion
    @MockBean
    private CoreV1Api coreApi;

```

2023-01-16 22:18 UTC, xhejtman commented on src/test/java/uk/ac/ebi/tsc/tesk/k8s/convert/TesKubernetesConverterMinimalTest.java
>  import org.springframework.util.StringUtils;
fixed

2023-01-16 22:18 UTC, xhejtman commented on src/test/java/uk/ac/ebi/tsc/tesk/k8s/convert/TesKubernetesConverterMinimalTest.java
fixed

2023-01-16 22:18 UTC, xhejtman commented on src/test/java/uk/ac/ebi/tsc/tesk/k8s/convert/TesKubernetesConverterMinimalTest.java
> +@ContextConfiguration(classes = {io.kubernetes.client.openapi.apis.CoreV1Api.class})
fixed

2023-01-16 22:18 UTC, xhejtman commented on src/test/java/uk/ac/ebi/tsc/tesk/k8s/convert/TesKubernetesConverterTest.java
> +@ContextConfiguration(classes = {io.kubernetes.client.openapi.apis.CoreV1Api.class})
fixed

2023-01-16 22:19 UTC, xhejtman commented
@lvarin thanks a lot! it is fixed now. so can we merge?

2023-01-17 12:09 UTC, lvarin commented
I will check today or tomorrow, sorry I had no time yet.

2023-01-17 12:51 UTC, martin-kuba approved these changes

2023-01-17 14:14 UTC, lvarin approved these changes

2023-01-17 14:14 UTC, lvarin commented
LGTM, it works out of the box in OpenShift (which is very picky with the security context)

2023-01-17 14:46 UTC, merged